### ISSUE TITLE
Does loader-esm understand npm_modules? 

### ISSUE THREAD

**Issue by alexdresko** [aurelia/loader-esm#1]
https://aurelia.io/blog/2018/11/04/aurelia-2018-q3-report/ links directly to this repo and there's no documentation here. Figured I'd start by asking the most important question I can think of. 

Does loader-esm understand npm_modules automatically?

**Comment by bigopon** [comment]
@alexdresko Thanks for checking it out. This loader is based on standard `import()` API, which means there is no module resolution, it always assume full path is provided. So you will want to do something like this: `node_modules/module/dist/some_file.js`
